const $=s=>document.querySelector(s);const money=v=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});const cats=['Alimentação','Mercado','Moradia','Transporte','Saúde','Educação','Lazer','Contas','Compras','Salário','Renda extra','Outros'];
const auth=$('#auth'),app=$('#app'),loginForm=$('#loginForm'),registerForm=$('#registerForm');let user=null;
const users=()=>JSON.parse(localStorage.getItem('cf_users')||'[]');const saveUsers=x=>localStorage.setItem('cf_users',JSON.stringify(x));async function hash(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
$('#showRegister').onclick=()=>{loginForm.classList.add('oculto');registerForm.classList.remove('oculto')};$('#backLogin').onclick=()=>{registerForm.classList.add('oculto');loginForm.classList.remove('oculto')};
registerForm.onsubmit=async e=>{e.preventDefault();let u=$('#regUser').value.trim().toLowerCase(),p=$('#regPass').value;if(p!==$('#regPass2').value){$('#regMsg').textContent='As senhas não coincidem.';return}let us=users();if(us.some(x=>x.user===u)){ $('#regMsg').textContent='Este usuário já existe.';return}us.push({name:$('#regName').value.trim(),user:u,pass:await hash(p)});saveUsers(us);registerForm.reset();$('#regMsg').textContent='Conta criada. Agora faça o login.';setTimeout(()=>$('#backLogin').click(),700)};
loginForm.onsubmit=async e=>{e.preventDefault();let u=$('#loginUser').value.trim().toLowerCase(),p=await hash($('#loginPass').value),found=users().find(x=>x.user===u&&x.pass===p);if(!found){$('#loginMsg').textContent='Usuário ou senha incorretos.';return}sessionStorage.setItem('cf_session',u);start(found)};
function start(found){user=found;auth.classList.add('oculto');app.classList.remove('oculto');$('#hello').textContent='Olá, '+found.name.split(' ')[0];let d=new Date();$('#monthFilter').value=d.toISOString().slice(0,7);render()}
$('#logout').onclick=()=>{sessionStorage.removeItem('cf_session');location.reload()};const key=()=>`cf_entries_${user.user}`;const entries=()=>JSON.parse(localStorage.getItem(key())||'[]');const save=x=>localStorage.setItem(key(),JSON.stringify(x));
cats.forEach(c=>{$('#category').add(new Option(c,c));$('#categoryFilter').add(new Option(c,c))});
const modal=$('#entryModal');$('#newEntry').onclick=()=>openEntry();$('#cancel').onclick=()=>modal.close();function openEntry(x){$('#entryForm').reset();$('#entryId').value=x?.id||'';$('#modalTitle').textContent=x?'Editar lançamento':'Novo lançamento';$('#date').value=x?.date||new Date().toISOString().slice(0,10);if(x){$('#desc').value=x.desc;$('#value').value=x.value;$('#type').value=x.type;$('#category').value=x.category;$('#payment').value=x.payment;$('#note').value=x.note||''}modal.showModal()}
$('#entryForm').onsubmit=e=>{e.preventDefault();let a=entries(),id=$('#entryId').value||crypto.randomUUID(),obj={id,desc:$('#desc').value.trim(),value:Number($('#value').value),date:$('#date').value,type:$('#type').value,category:$('#category').value,payment:$('#payment').value,note:$('#note').value.trim()};let i=a.findIndex(x=>x.id===id);i>=0?a[i]=obj:a.push(obj);save(a);modal.close();render()};
function filtered(){let m=$('#monthFilter').value,c=$('#categoryFilter').value,q=$('#search').value.toLowerCase();return entries().filter(x=>(!m||x.date.startsWith(m))&&(!c||x.category===c)&&(!q||`${x.desc} ${x.category} ${x.note}`.toLowerCase().includes(q))).sort((a,b)=>b.date.localeCompare(a.date))}
function render(){let a=filtered(),inc=a.filter(x=>x.type==='income').reduce((s,x)=>s+x.value,0),exp=a.filter(x=>x.type==='expense').reduce((s,x)=>s+x.value,0);$('#income').textContent=money(inc);$('#expense').textContent=money(exp);$('#balance').textContent=money(inc-exp);$('#count').textContent=a.length;$('#rows').innerHTML=a.map(x=>`<tr><td>${x.date.split('-').reverse().join('/')}</td><td><strong>${esc(x.desc)}</strong><br><small>${esc(x.payment)}</small></td><td><span class="tag">${esc(x.category)}</span></td><td>${x.type==='income'?'Receita':'Despesa'}</td><td class="valor-${x.type}">${x.type==='income'?'+':'-'} ${money(x.value)}</td><td class="actions"><button onclick="editEntry('${x.id}')" title="Editar">✏️</button><button onclick="delEntry('${x.id}')" title="Excluir">🗑️</button></td></tr>`).join('');$('#empty').classList.toggle('oculto',a.length>0);renderCats(a)}
function renderCats(a){let e=a.filter(x=>x.type==='expense'),tot=e.reduce((s,x)=>s+x.value,0),map={};e.forEach(x=>map[x.category]=(map[x.category]||0)+x.value);let ar=Object.entries(map).sort((a,b)=>b[1]-a[1]);$('#categorySummary').innerHTML=ar.length?ar.map(([c,v])=>`<div class="cat-row"><strong>${esc(c)}</strong><span>${money(v)}</span><div class="bar"><i style="width:${tot?v/tot*100:0}%"></i></div></div>`).join(''):'<div class="vazio">Sem despesas neste período.</div>'}
window.editEntry=id=>openEntry(entries().find(x=>x.id===id));window.delEntry=id=>{if(confirm('Excluir este lançamento?')){save(entries().filter(x=>x.id!==id));render()}};function esc(s=''){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}['monthFilter','categoryFilter','search'].forEach(id=>$('#'+id).addEventListener('input',render));
let sess=sessionStorage.getItem('cf_session');if(sess){let found=users().find(x=>x.user===sess);if(found)start(found)}
